export const SET_LOADING = "SET_LOADING";
export const SET_SHOW_PASSWORD = "SET_SHOW_PASSWORD";
export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_TEST_CREDENTIALS = "SET_TEST_CREDENTIALS";
