export const SET_CATEGORIES = "SET_CATEGORIES";
export const INITIALIZE_QUIZ = "INITIALIZE_QUIZ";
export const SET_LEADERBOARD = "SET_LEADERBOARD";
export const SET_USER_RESULTS = "SET_USER_RESULTS";
export const SET_SELECTED_OPTION = "SET_SELECTED_OPTION";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
