export const SET_SCORE = "SET_SCORE";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const INITIALIZE_QUIZ = "INITIALIZE_QUIZ";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
